config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :users, only: [:index, :show]
  resources :posts, only: [:index,:new,:show,:create,:destroy] do
    resources :likes, only: [:create, :destroy]
  end
  
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_count
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :body, :image, presence: true
  
  belongs_to :user
  has_many :likes
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:show, :new, :create]
  def index
   @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def show 
    @post = Post.find(params[:id])
    @like = Like.new
  end

  def create
    @post = Post.create(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy 
  end


  private
  def post_params
    params.require(:post).permit(:body, :image).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout 'user-show', only: :show
  def index
    @users = User.all
  end

  def show 
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_heder.html.erb
 <div class="header">
  <h1 class="header-title">
  <%= link_to "Favorite", root_path, class: "header__title" %>
  </h1>
  <ul class="header-logo">
    <%= link_to  new_post_path do%>
      <li><i class="far fa-edit fa-2x"></i></li>
    <% end %>
  </ul>
  <% if user_signed_in? %>
    <div class="user_nav grid-6">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  
    </div>
  <% else %>
    <div class="grid-6">
      <%= link_to "ログイン", new_user_session_path, class: 'post' %>
      <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favorite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta charset="utf-8">
    <link rel="stylesheets" href="_reset.scss" >
    <link rel="stylesheets" href="_post.scss" >
    <link rel="stylesheets" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
   <div class="wrapper">
      <div class="header">
        <h1 class="header-title">
         <%= link_to "Favorite", root_path, class: "header__title" %>
        </h1>
        <ul class="header-logo">
          <%= link_to  new_post_path do%>
            <li><i class="far fa-edit fa-2x"></i></li>
          <% end %>
        </ul>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>

      </div>
    </div>
    <div class="content">
    <%= yield %>
  </body>
</html>

app/views/layouts/user-show.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Favorite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta charset="utf-8">
    <link rel="stylesheets" href="_reset.scss" >
    <link rel="stylesheets" href="_post.scss" >
    <link rel="stylesheets" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
  </head>

  <body>
    <div class="user-show-contents">
      <div class="user-show-contents__box-left">
        <div class= "user-detail-box">
          <p><i class= "fas fa-user-alt fa-5x "></i></p>
          <h2 class="username"> <%= @user.nickname %> 

        </div>
      </div>
      <div class="user-show-contents__box-main">
       <h2>------------投稿した内容------------</h2>
       
        <div class= "post-box">
          <% @user.posts.each do |post| %>
            <%= render partial: "posts/post", locals: { post: post }%>
          <% end %>
        </div>
        <h2>----------いいねした内容-----------</h2>
        <div class= "good-box">
          <% @user.liked_posts.each do |post| %>
            <%= render partial: "posts/post", locals: { post: post }%>       
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if post.like_user(current_user.id) %>
    <%= button_to post_like_path(like, post_id: post.id), method: :delete, id: "like-button", remote: true do %>
      <%= image_tag("far fa-edit fa-2x") %>
      <span>
        <%= post.like_count %>
      </span>
    <% end %>
  <% else %>
    <%= button_to post_likes_path(post), id: "like-button", remote: true do %>
      <%= image_tag("icon_heart.svg") %>
      <span>
        <%= post.like_count %>
      </span>
    <% end %>
  <% end %>
<% else %>
  <% = image_tag("icon_heart.svg") %>
    <span>
      <%= post.like_count %>
    </span>
<% end %>

app/views/likes/destroy.js.erb
$("#like-buttons").html("<%= j(render partial: 'like', locals: { posts: @posts, likes: @likes }) %>");

app/views/posts/_post.html.erb
<div class="message-box">
            <div class="box-top">
              <div class="name">
                <%= post.user.nickname %>
              </div>
              <div class="more">
                <ul class = "more_list"> 
                  <% if user_signed_in? && current_user.id == post.user_id %>
                    <li>
                      <%= link_to '削除',"/posts/#{post.id}", method: :delete %>
                    </li>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="box-center">
              <div class="text-box">
                <%= post.body %>
              </div>
              <div class="image-box">
                <% if post.image? %>
                <%= image_tag post.image.url, :size =>'400x350' %>
                <% end %>
              <div>
            </div>
            <%# <div class="box-bottom">
              <div class="good-btn">
                <i class="fas fa-heart fa-2x"></i>
              </div>
            </div> %>
        </div>
      </div>
    </div>

app/views/posts/destroy.html.erb
<div class="contents-row">
  <div class="success">
    <h3>
      削除が完了しました。
    </h3>
    <a class="btn" href="/">投稿一覧へ戻る</a>
  </div>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<%= render partial: "post", locals: { post: post }%>
<% end %>
<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
  <%= link_to "ユーザー一覧へ", users_path %>
  <hr> 
  <h2>投稿一覧</h2>
  <% @posts.each do |post| %>
    <a href="/users/<%= post.user.id %>"><%= post.user.nickname %></a>
    <a href="/posts/<%= post.id %>"><%= post.body %></a>
    (<%= post.liked_users.count %>)
  <% end %>
<% end %>

app/views/posts/new.html.erb
<%= form_with model: @post, class: :form, local: true do |form| %>
  <%= form.text_area :body,placeholeder: :本文, class: :form__text%>
  <%= form.file_field :image, class: :form__image%> 
  <%= form.submit '投稿', class: :form__btn %>
<% end %>

app/views/posts/show.html.erb
<div class= contents-show>
  <h1>投稿詳細ページ</h1>
  <h3><%= @post.user.nickname %></h2>
  <h3><%= @post.body %></h2>
  <h3>いいね件数: <%= @post.likes.count %></h3>
  <% if current_user.already_liked?(@post) %>
    <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
  <% else %>
    <%= button_to 'いいね', post_likes_path(@post) %>
  <% end %>
  <h4>いいねしたユーザー</h2>
  <% @post.liked_users.each do |user| %>
    <li><%= user.nickname %></li>
  <% end %>

  <%= link_to "ホームへ戻る", posts_path %>
</div>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>
<% @users.each do |user| %>
   <p> <%= user.nickname %> </p>
   <hr>
<% end %>
<%= link_to "ホームへ戻る", posts_path %>